/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_luffy_directundist_CamRenderer */

#ifndef _Included_com_example_luffy_directundist_CamRenderer
#define _Included_com_example_luffy_directundist_CamRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_luffy_directundist_CamRenderer
 * Method:    drawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_luffy_directundist_CamRenderer_drawFrame
  (JNIEnv *, jobject);

/*
 * Class:     com_example_luffy_directundist_CamRenderer
 * Method:    initDraw
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_luffy_directundist_CamRenderer_initDraw
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
