/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_luffy_directundist_CamSurface */

#ifndef _Included_com_example_luffy_directundist_CamSurface
#define _Included_com_example_luffy_directundist_CamSurface
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_luffy_directundist_CamSurface_MAGIC_TEXTURE_ID
#define com_example_luffy_directundist_CamSurface_MAGIC_TEXTURE_ID 10L
/*
 * Class:     com_example_luffy_directundist_CamSurface
 * Method:    processFrame
 * Signature: ([BIIIZZ)V
 */
JNIEXPORT void JNICALL Java_com_example_luffy_directundist_CamSurface_processFrame
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
